version: 0.2

phases:
  pre_build:
    commands:
      - echo "Updating kubeconfig for EKS cluster..."
      - aws eks update-kubeconfig --name shital-eks-cluster --region us-east-1
      - kubectl config get-contexts
      - echo "Current context set to $(kubectl config current-context)"

  build:
    commands:
      - echo "Restarting pods for microservices in namespace shital-ns..."
      # - kubectl apply -f k8s-manifests/ -n shital-ns   

      # Restart each deployment
      - kubectl rollout restart deployment/admin-service -n shital-ns
      - kubectl rollout restart deployment/order-service -n shital-ns
      - kubectl rollout restart deployment/product-service -n shital-ns
      - kubectl rollout restart deployment/enn-ecommerce-app -n shital-ns   # Angular app

      # Optional: wait for rollout to complete
      - kubectl rollout status deployment/admin-service -n shital-ns
      - kubectl rollout status deployment/order-service -n shital-ns
      - kubectl rollout status deployment/product-service -n shital-ns
      - kubectl rollout status deployment/enn-ecommerce-app -n shital-ns

  post_build:
    commands:
      - echo "Pods restarted successfully!"
      - echo "Listing pods in shital-ns:"
      - kubectl get pods -n shital-ns
      - echo "Listing services in shital-ns:"
      - kubectl get svc -n shital-ns

artifacts:
  files:
    - '**/*'
